version: "3.7"

services:
  postgres:
    image: postgres:12.3
    hostname: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: depscloud
    ports:
    - 5432:5432

  tracker:
    image: depscloud/tracker:latest
    hostname: tracker
    depends_on:
    - postgres
    command:
    - --storage-driver=pgx
    - --storage-address=postgres://user:password@postgres:5432/depscloud

  extractor:
    image: depscloud/extractor:latest
    hostname: extractor
    
  indexer:
    image: depscloud/indexer:latest
    hostname: indexer
    depends_on:
    - extractor
    - tracker
    volumes:
    - ./rds.yaml:/etc/rds/config.yaml
    command:
    - --cron
    - --rds-config=/etc/rds/config.yaml
    - --workers=1

  gateway:
    image: depscloud/gateway:latest
    hostname: gateway
    depends_on:
    - extractor
    - tracker
    ports:
    - 8080:8080
